# World-space configuration
VIEW_HEIGHT = 7.5
ASSET_PPU = 24.0

# Sprite frame dimensions
FRAME_WIDTH_PX = 56
FRAME_HEIGHT_PX = 56
COLUMNS = 7
FRAME_WIDTH = FRAME_WIDTH_PX / ASSET_PPU
FRAME_HEIGHT = FRAME_HEIGHT_PX / ASSET_PPU

# Window and resolution
WINDOW_WIDTH = 960
WINDOW_HEIGHT = 540
RETRO_WIDTH = 128
RETRO_HEIGHT = 128

# Physics
GRAVITY = 33.33
MOVE_SPEED = 8.33
JUMP_FORCE = -16.67

# Audio
SFX_VOLUME = 0.5
MUSIC_VOLUME = 0.7

# Tilemap
TILE_SIZE_PX = 24
TILE_SIZE = 1.0
TILESET_COLS = 21
MAP_WIDTH = 80
MAP_HEIGHT = 25
MAP_OFFSET_X = -8.33
MAP_OFFSET_Y = 0.0

# Camera
CAMERA_OFFSET_Y_PERCENT = 0.7
CAMERA_SMOOTHING = 0.85
CAMERA_DEADZONE_WIDTH = 1.0
CAMERA_DEADZONE_HEIGHT = 0.5

# Parallax
BG_LAYER_WIDTH = 320.0 / ASSET_PPU
BG_PARALLAX_1 = 0.1
BG_PARALLAX_2 = 0.3
BG_PARALLAX_3 = 0.5

# Screen shake
ATTACK_SHAKE_STRENGTH = 0.25
ATTACK_SHAKE_DURATION = 0.30

# Character hitbox
CHAR_HITBOX_OFFSET_X = 0.625
CHAR_HITBOX_OFFSET_Y = 0.33
CHAR_HITBOX_WIDTH = 1.08
CHAR_HITBOX_HEIGHT = 2.0

# Wall configuration
WALL_WIDTH = 10

module Tiles
  GROUND_TOP_LEFT     = 0
  GROUND_TOP_CENTER   = 1
  GROUND_TOP_RIGHT    = 2
  GROUND_MID_LEFT     = 21
  GROUND_MID_CENTER   = 22
  GROUND_MID_RIGHT    = 23
  GROUND_BOT_LEFT     = 42
  GROUND_BOT_CENTER   = 43
  GROUND_BOT_RIGHT    = 44
  PLAT_TOP_LEFT       = 3
  PLAT_TOP_CENTER     = 4
  PLAT_TOP_RIGHT      = 5
  PLAT_MID_LEFT       = 24
  PLAT_MID_CENTER     = 25
  PLAT_MID_RIGHT      = 26
  PLAT_BOT_LEFT       = 45
  PLAT_BOT_CENTER     = 46
  PLAT_BOT_RIGHT      = 47
  COLUMN_TOP          = 63
  COLUMN_MID          = 84
  COLUMN_BOT          = 105
  THIN_LEFT           = 126
  THIN_CENTER         = 127
  THIN_RIGHT          = 128
  ALT_TOP_LEFT        = 6
  ALT_TOP_CENTER      = 7
  ALT_TOP_RIGHT       = 8
  INNER_TOP_LEFT      = 9
  INNER_TOP_RIGHT     = 11
  INNER_BOT_LEFT      = 51
  INNER_BOT_RIGHT     = 53
  DECO_GRASS_1        = 189
  DECO_GRASS_2        = 190
  DECO_ROCK_1         = 210
  DECO_ROCK_2         = 211

  SOLID_TILES = [
    GROUND_TOP_LEFT, GROUND_TOP_CENTER, GROUND_TOP_RIGHT,
    GROUND_MID_LEFT, GROUND_MID_CENTER, GROUND_MID_RIGHT,
    GROUND_BOT_LEFT, GROUND_BOT_CENTER, GROUND_BOT_RIGHT,
    PLAT_TOP_LEFT, PLAT_TOP_CENTER, PLAT_TOP_RIGHT,
    PLAT_MID_LEFT, PLAT_MID_CENTER, PLAT_MID_RIGHT,
    PLAT_BOT_LEFT, PLAT_BOT_CENTER, PLAT_BOT_RIGHT,
    ALT_TOP_LEFT, ALT_TOP_CENTER, ALT_TOP_RIGHT,
    THIN_LEFT, THIN_CENTER, THIN_RIGHT,
    COLUMN_TOP, COLUMN_MID, COLUMN_BOT
  ].freeze
end
